name: Release Build

on:
  push:
    paths:
      - "run.py"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller geopy pillow openai piexif ttkbootstrap python-dotenv

    - name: Compile Windows Executable
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico --name SmartPhotoMetadata run.py

    - name: Compile Linux Executable
      if: runner.os == 'Linux'
      run: |
        pyinstaller --onefile --name SmartPhotoMetadata run.py

    - name: Upload Windows Executable
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: SmartPhotoMetadata-Windows
        path: dist/SmartPhotoMetadata.exe

    - name: Upload Linux Executable
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: SmartPhotoMetadata-Linux
        path: dist/SmartPhotoMetadata

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Windows Executable
      uses: actions/download-artifact@v4
      with:
        name: SmartPhotoMetadata-Windows
        path: .

    - name: Download Linux Executable
      uses: actions/download-artifact@v4
      with:
        name: SmartPhotoMetadata-Linux
        path: .

    - name: Verify Files Exist
      run: |
        ls -l

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GH_PAT }}
        tag_name: release-${{ github.run_number }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          SmartPhotoMetadata.exe
          SmartPhotoMetadata
        body: |
          ### 🚀 New Release: ${{ github.ref_name }}

          **SmartPhotoMetadata Changelog**

          - Automatically built and released using GitHub Actions.
          - Supports Windows (`.exe`) and Linux (`.tar.gz`).